// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authors.sql

package db

import (
	"context"
)

const linkBookAuthor = `-- name: LinkBookAuthor :exec
INSERT INTO book_authors (book_id, author_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkBookAuthorParams struct {
	BookID   int64 `json:"book_id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) LinkBookAuthor(ctx context.Context, arg LinkBookAuthorParams) error {
	_, err := q.db.Exec(ctx, linkBookAuthor, arg.BookID, arg.AuthorID)
	return err
}

const upsertAuthor = `-- name: UpsertAuthor :one
INSERT INTO authors (name, slug, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    updated_at = NOW()
RETURNING id, name, slug, created_at, updated_at
`

type UpsertAuthorParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, upsertAuthor, arg.Name, arg.Slug)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
