// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authors_sqlite.sql

package db

import (
	"context"
)

const getFirstAuthorForBook = `-- name: GetFirstAuthorForBook :one
SELECT a.name FROM authors a
JOIN book_authors ba ON ba.author_id = a.id
WHERE ba.book_id = ? LIMIT 1
`

func (q *Queries) GetFirstAuthorForBook(ctx context.Context, bookID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getFirstAuthorForBook, bookID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const linkBookAuthor = `-- name: LinkBookAuthor :exec
INSERT INTO book_authors (book_id, author_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type LinkBookAuthorParams struct {
	BookID   int64 `json:"book_id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) LinkBookAuthor(ctx context.Context, arg LinkBookAuthorParams) error {
	_, err := q.db.ExecContext(ctx, linkBookAuthor, arg.BookID, arg.AuthorID)
	return err
}

const listAuthors = `-- name: ListAuthors :many
SELECT a.id, a.name, a.slug, COUNT(ba.book_id) AS book_count
FROM authors a
LEFT JOIN book_authors ba ON ba.author_id = a.id
GROUP BY a.id
ORDER BY a.name ASC
`

type ListAuthorsRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	BookCount int64  `json:"book_count"`
}

func (q *Queries) ListAuthors(ctx context.Context) ([]ListAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsRow
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAuthor = `-- name: UpsertAuthor :one
INSERT INTO authors (name, slug, created_at, updated_at)
VALUES (?, ?, datetime('now'), datetime('now'))
ON CONFLICT (slug) DO UPDATE SET
    name       = excluded.name,
    updated_at = datetime('now')
RETURNING id, name, slug, created_at, updated_at
`

type UpsertAuthorParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, upsertAuthor, arg.Name, arg.Slug)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
