// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package db

import (
	"context"
)

const getBookBySlug = `-- name: GetBookBySlug :one
SELECT id, goodreads_id, slug, title, description, cover_path, page_count, publication_year, isbn13, metadata_source, read_at, date_added, read_count, shelf, search_vector, created_at, updated_at FROM books WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetBookBySlug(ctx context.Context, slug string) (Book, error) {
	row := q.db.QueryRow(ctx, getBookBySlug, slug)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.GoodreadsID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.CoverPath,
		&i.PageCount,
		&i.PublicationYear,
		&i.Isbn13,
		&i.MetadataSource,
		&i.ReadAt,
		&i.DateAdded,
		&i.ReadCount,
		&i.Shelf,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, goodreads_id, slug, title, description, cover_path, page_count, publication_year, isbn13, metadata_source, read_at, date_added, read_count, shelf, search_vector, created_at, updated_at FROM books ORDER BY read_at DESC NULLS LAST, id DESC
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.GoodreadsID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.CoverPath,
			&i.PageCount,
			&i.PublicationYear,
			&i.Isbn13,
			&i.MetadataSource,
			&i.ReadAt,
			&i.DateAdded,
			&i.ReadCount,
			&i.Shelf,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
