// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books_sqlite.sql

package db

import (
	"context"
)

const getAllGoodreadsIDs = `-- name: GetAllGoodreadsIDs :many
SELECT goodreads_id, slug, shelf FROM books
`

type GetAllGoodreadsIDsRow struct {
	GoodreadsID string `json:"goodreads_id"`
	Slug        string `json:"slug"`
	Shelf       string `json:"shelf"`
}

func (q *Queries) GetAllGoodreadsIDs(ctx context.Context) ([]GetAllGoodreadsIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllGoodreadsIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGoodreadsIDsRow
	for rows.Next() {
		var i GetAllGoodreadsIDsRow
		if err := rows.Scan(&i.GoodreadsID, &i.Slug, &i.Shelf); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnenrichedBooks = `-- name: GetUnenrichedBooks :many
SELECT id, goodreads_id, slug, title, description, cover_path, page_count,
       publication_year, isbn13, metadata_source, read_at, date_added,
       read_count, shelf, created_at, updated_at
FROM books WHERE metadata_source = 'none' ORDER BY created_at ASC
`

func (q *Queries) GetUnenrichedBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getUnenrichedBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.GoodreadsID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.CoverPath,
			&i.PageCount,
			&i.PublicationYear,
			&i.Isbn13,
			&i.MetadataSource,
			&i.ReadAt,
			&i.DateAdded,
			&i.ReadCount,
			&i.Shelf,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBooks = `-- name: ListAllBooks :many
SELECT
  b.id, b.slug, b.title, b.cover_path, b.read_at, b.publication_year,
  b.page_count, b.description, b.isbn13, b.read_count, b.shelf, b.metadata_source,
  (SELECT json_group_array(json_object('name', a.name, 'slug', a.slug))
   FROM book_authors ba JOIN authors a ON a.id = ba.author_id
   WHERE ba.book_id = b.id) AS authors_json,
  (SELECT json_group_array(json_object('name', g.name, 'slug', g.slug))
   FROM book_genres bg JOIN genres g ON g.id = bg.genre_id
   WHERE bg.book_id = b.id) AS genres_json
FROM books b
ORDER BY b.read_at DESC, b.id DESC
`

type ListAllBooksRow struct {
	ID              int64       `json:"id"`
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	CoverPath       *string     `json:"cover_path"`
	ReadAt          *string     `json:"read_at"`
	PublicationYear *int64      `json:"publication_year"`
	PageCount       *int64      `json:"page_count"`
	Description     *string     `json:"description"`
	Isbn13          *string     `json:"isbn13"`
	ReadCount       int64       `json:"read_count"`
	Shelf           string      `json:"shelf"`
	MetadataSource  string      `json:"metadata_source"`
	AuthorsJson     interface{} `json:"authors_json"`
	GenresJson      interface{} `json:"genres_json"`
}

func (q *Queries) ListAllBooks(ctx context.Context) ([]ListAllBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBooksRow
	for rows.Next() {
		var i ListAllBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.CoverPath,
			&i.ReadAt,
			&i.PublicationYear,
			&i.PageCount,
			&i.Description,
			&i.Isbn13,
			&i.ReadCount,
			&i.Shelf,
			&i.MetadataSource,
			&i.AuthorsJson,
			&i.GenresJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookEnrichment = `-- name: UpdateBookEnrichment :exec
UPDATE books SET
    description      = ?,
    page_count       = ?,
    publication_year = ?,
    cover_path       = ?,
    metadata_source  = ?,
    updated_at       = datetime('now')
WHERE id = ?
`

type UpdateBookEnrichmentParams struct {
	Description     *string `json:"description"`
	PageCount       *int64  `json:"page_count"`
	PublicationYear *int64  `json:"publication_year"`
	CoverPath       *string `json:"cover_path"`
	MetadataSource  string  `json:"metadata_source"`
	ID              int64   `json:"id"`
}

func (q *Queries) UpdateBookEnrichment(ctx context.Context, arg UpdateBookEnrichmentParams) error {
	_, err := q.db.ExecContext(ctx, updateBookEnrichment,
		arg.Description,
		arg.PageCount,
		arg.PublicationYear,
		arg.CoverPath,
		arg.MetadataSource,
		arg.ID,
	)
	return err
}

const upsertBook = `-- name: UpsertBook :one
INSERT INTO books (
    goodreads_id, slug, title, description, cover_path, page_count,
    publication_year, isbn13, metadata_source, read_at, date_added,
    read_count, shelf, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now')
)
ON CONFLICT (goodreads_id) DO UPDATE SET
    slug       = excluded.slug,
    title      = excluded.title,
    read_at    = excluded.read_at,
    date_added = excluded.date_added,
    read_count = excluded.read_count,
    shelf      = excluded.shelf,
    updated_at = datetime('now')
RETURNING id, goodreads_id, slug, title, description, cover_path, page_count,
          publication_year, isbn13, metadata_source, read_at, date_added,
          read_count, shelf, created_at, updated_at
`

type UpsertBookParams struct {
	GoodreadsID     string  `json:"goodreads_id"`
	Slug            string  `json:"slug"`
	Title           string  `json:"title"`
	Description     *string `json:"description"`
	CoverPath       *string `json:"cover_path"`
	PageCount       *int64  `json:"page_count"`
	PublicationYear *int64  `json:"publication_year"`
	Isbn13          *string `json:"isbn13"`
	MetadataSource  string  `json:"metadata_source"`
	ReadAt          *string `json:"read_at"`
	DateAdded       *string `json:"date_added"`
	ReadCount       int64   `json:"read_count"`
	Shelf           string  `json:"shelf"`
}

func (q *Queries) UpsertBook(ctx context.Context, arg UpsertBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, upsertBook,
		arg.GoodreadsID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.CoverPath,
		arg.PageCount,
		arg.PublicationYear,
		arg.Isbn13,
		arg.MetadataSource,
		arg.ReadAt,
		arg.DateAdded,
		arg.ReadCount,
		arg.Shelf,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.GoodreadsID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.CoverPath,
		&i.PageCount,
		&i.PublicationYear,
		&i.Isbn13,
		&i.MetadataSource,
		&i.ReadAt,
		&i.DateAdded,
		&i.ReadCount,
		&i.Shelf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
