// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: genres.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGenreBySlug = `-- name: GetGenreBySlug :one
SELECT g.id, g.name, g.slug
FROM genres g
WHERE g.slug = $1
`

type GetGenreBySlugRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) GetGenreBySlug(ctx context.Context, slug string) (GetGenreBySlugRow, error) {
	row := q.db.QueryRow(ctx, getGenreBySlug, slug)
	var i GetGenreBySlugRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const linkBookGenre = `-- name: LinkBookGenre :exec
INSERT INTO book_genres (book_id, genre_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkBookGenreParams struct {
	BookID  int64 `json:"book_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) LinkBookGenre(ctx context.Context, arg LinkBookGenreParams) error {
	_, err := q.db.Exec(ctx, linkBookGenre, arg.BookID, arg.GenreID)
	return err
}

const listBooksByGenre = `-- name: ListBooksByGenre :many
SELECT
    b.id, b.slug, b.title, b.cover_path, b.read_at, b.publication_year,
    COALESCE(
        json_agg(DISTINCT jsonb_build_object('name', a.name, 'slug', a.slug))
        FILTER (WHERE a.id IS NOT NULL), '[]'
    ) AS authors,
    COALESCE(
        json_agg(DISTINCT jsonb_build_object('name', g2.name, 'slug', g2.slug))
        FILTER (WHERE g2.id IS NOT NULL), '[]'
    ) AS genres
FROM books b
JOIN book_genres bg ON bg.book_id = b.id
JOIN genres g ON g.id = bg.genre_id
LEFT JOIN book_authors ba ON ba.book_id = b.id
LEFT JOIN authors a ON a.id = ba.author_id
LEFT JOIN book_genres bg2 ON bg2.book_id = b.id
LEFT JOIN genres g2 ON g2.id = bg2.genre_id
WHERE g.slug = $1
  AND ($2::timestamptz IS NULL OR (b.read_at, b.id) < ($2::timestamptz, $3::bigint))
GROUP BY b.id
ORDER BY b.read_at DESC NULLS LAST, b.id DESC
LIMIT $4
`

type ListBooksByGenreParams struct {
	Slug    string             `json:"slug"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 int64              `json:"column_3"`
	Limit   int32              `json:"limit"`
}

type ListBooksByGenreRow struct {
	ID              int64              `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	CoverPath       *string            `json:"cover_path"`
	ReadAt          pgtype.Timestamptz `json:"read_at"`
	PublicationYear *int32             `json:"publication_year"`
	Authors         interface{}        `json:"authors"`
	Genres          interface{}        `json:"genres"`
}

func (q *Queries) ListBooksByGenre(ctx context.Context, arg ListBooksByGenreParams) ([]ListBooksByGenreRow, error) {
	rows, err := q.db.Query(ctx, listBooksByGenre,
		arg.Slug,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksByGenreRow
	for rows.Next() {
		var i ListBooksByGenreRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.CoverPath,
			&i.ReadAt,
			&i.PublicationYear,
			&i.Authors,
			&i.Genres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenres = `-- name: ListGenres :many
SELECT g.id, g.name, g.slug, COUNT(bg.book_id)::bigint AS book_count
FROM genres g
LEFT JOIN book_genres bg ON bg.genre_id = g.id
GROUP BY g.id
ORDER BY COUNT(bg.book_id) DESC, g.name COLLATE "und-x-icu" ASC
`

type ListGenresRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	BookCount int64  `json:"book_count"`
}

func (q *Queries) ListGenres(ctx context.Context) ([]ListGenresRow, error) {
	rows, err := q.db.Query(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenresRow
	for rows.Next() {
		var i ListGenresRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYears = `-- name: ListYears :many
SELECT
    EXTRACT(YEAR FROM read_at)::int AS year,
    COUNT(*)::bigint AS book_count
FROM books
WHERE read_at IS NOT NULL AND shelf = 'read'
GROUP BY EXTRACT(YEAR FROM read_at)
ORDER BY year DESC
`

type ListYearsRow struct {
	Year      int32 `json:"year"`
	BookCount int64 `json:"book_count"`
}

func (q *Queries) ListYears(ctx context.Context) ([]ListYearsRow, error) {
	rows, err := q.db.Query(ctx, listYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListYearsRow
	for rows.Next() {
		var i ListYearsRow
		if err := rows.Scan(&i.Year, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGenre = `-- name: UpsertGenre :one
INSERT INTO genres (name, slug, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    updated_at = NOW()
RETURNING id, name, slug, created_at, updated_at
`

type UpsertGenreParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpsertGenre(ctx context.Context, arg UpsertGenreParams) (Genre, error) {
	row := q.db.QueryRow(ctx, upsertGenre, arg.Name, arg.Slug)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
