// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: genres.sql

package db

import (
	"context"
)

const linkBookGenre = `-- name: LinkBookGenre :exec
INSERT INTO book_genres (book_id, genre_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkBookGenreParams struct {
	BookID  int64 `json:"book_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) LinkBookGenre(ctx context.Context, arg LinkBookGenreParams) error {
	_, err := q.db.Exec(ctx, linkBookGenre, arg.BookID, arg.GenreID)
	return err
}

const upsertGenre = `-- name: UpsertGenre :one
INSERT INTO genres (name, slug, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    updated_at = NOW()
RETURNING id, name, slug, created_at, updated_at
`

type UpsertGenreParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpsertGenre(ctx context.Context, arg UpsertGenreParams) (Genre, error) {
	row := q.db.QueryRow(ctx, upsertGenre, arg.Name, arg.Slug)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
