// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: genres_sqlite.sql

package db

import (
	"context"
)

const linkBookGenre = `-- name: LinkBookGenre :exec
INSERT INTO book_genres (book_id, genre_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type LinkBookGenreParams struct {
	BookID  int64 `json:"book_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) LinkBookGenre(ctx context.Context, arg LinkBookGenreParams) error {
	_, err := q.db.ExecContext(ctx, linkBookGenre, arg.BookID, arg.GenreID)
	return err
}

const listGenres = `-- name: ListGenres :many
SELECT g.id, g.name, g.slug, COUNT(bg.book_id) AS book_count
FROM genres g
LEFT JOIN book_genres bg ON bg.genre_id = g.id
GROUP BY g.id
ORDER BY book_count DESC, g.name ASC
`

type ListGenresRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	BookCount int64  `json:"book_count"`
}

func (q *Queries) ListGenres(ctx context.Context) ([]ListGenresRow, error) {
	rows, err := q.db.QueryContext(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenresRow
	for rows.Next() {
		var i ListGenresRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGenre = `-- name: UpsertGenre :one
INSERT INTO genres (name, slug, created_at, updated_at)
VALUES (?, ?, datetime('now'), datetime('now'))
ON CONFLICT (slug) DO UPDATE SET
    name       = excluded.name,
    updated_at = datetime('now')
RETURNING id, name, slug, created_at, updated_at
`

type UpsertGenreParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpsertGenre(ctx context.Context, arg UpsertGenreParams) (Genre, error) {
	row := q.db.QueryRowContext(ctx, upsertGenre, arg.Name, arg.Slug)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
