// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Book struct {
	ID              int64              `json:"id"`
	GoodreadsID     string             `json:"goodreads_id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Description     *string            `json:"description"`
	CoverPath       *string            `json:"cover_path"`
	PageCount       *int32             `json:"page_count"`
	PublicationYear *int32             `json:"publication_year"`
	Isbn13          *string            `json:"isbn13"`
	MetadataSource  string             `json:"metadata_source"`
	ReadAt          pgtype.Timestamptz `json:"read_at"`
	DateAdded       pgtype.Timestamptz `json:"date_added"`
	ReadCount       int32              `json:"read_count"`
	Shelf           string             `json:"shelf"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type BookAuthor struct {
	BookID   int64 `json:"book_id"`
	AuthorID int64 `json:"author_id"`
}

type BookGenre struct {
	BookID  int64 `json:"book_id"`
	GenreID int64 `json:"genre_id"`
}

type Genre struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
